name: CI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  docker_build_spacelift-runner:
    name: Docker spacelift-runner
    uses: ./.github/workflows/template_docker_build.yaml
    with:
      push: true
      file_name: spacelift-runner.Dockerfile
      image_name: spacelift-runner
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
