name: Draft release notes
on:
  push:
    branches:
      - main

jobs:
  release_notes:
    name: Update release notes
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        name: Generate release notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
